# Eureka
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

# Management
management:
  context-path: /
  security:
    enabled: false # just to see the zuul routes (/routes endpoint) without type a password

logging:
  level:
    com.netflix.discovery: 'ERROR'
    org.springframework.cloud: 'INFO'

# Server
server:
  port: ${info.application.port}
  tomcat:
    accesslog:
      enabled: true
      directory: ${logging.path}/
      prefix: access_log_${spring.application.index}
  compression:
    enabled: true

---

spring:
  profiles: development

logging:
  level:
    com.netflix.discovery: 'OFF'
